package convex.core.cpos;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.util.HashMap;

import org.junit.jupiter.api.Test;

import convex.core.cvm.CVMEncoder;
import convex.core.data.ACell;
import convex.core.data.AEncoder.DecodeState;
import convex.core.data.Blob;
import convex.core.data.Format;
import convex.core.data.Hash;
import convex.test.Samples;
/**
 * Tests decoding a real Belief snapshot from CAD3 multi-cell format
 * using the DecodeState path.
 *
 * belief-1771151911735.cad3 is committed to test resources (generated by AcquireBelief).
 */
public class BeliefSnapshotTest {

	static final String BELIEF_FILE = "/belief-1771151911735.cad3";

	private static Blob beliefBlob;
	private static Belief belief;

	public static synchronized Blob getBeliefBlob() {
		if (beliefBlob == null) loadBelief();
		return beliefBlob;
	}

	public static synchronized Belief getBelief() {
		if (belief == null) loadBelief();
		return belief;
	}

	private static void loadBelief() {
		try (InputStream is = BeliefSnapshotTest.class.getResourceAsStream(BELIEF_FILE)) {
			assertNotNull(is, BELIEF_FILE + " not found in test resources");
			beliefBlob = Blob.wrap(is.readAllBytes());
		} catch (Exception e) {
			throw new RuntimeException("Failed to load " + BELIEF_FILE, e);
		}
		assertTrue(beliefBlob.count() > 100, "Belief file too small");

		try {
			ACell result = Samples.TEST_STORE.decodeMultiCell(beliefBlob);
			assertInstanceOf(Belief.class, result);
			belief = (Belief) result;
		} catch (Exception e) {
			throw new RuntimeException("Failed to decode " + BELIEF_FILE, e);
		}
	}

	@Test
	public void testBeliefRecord() {
		BeliefTest.doBeliefTests(getBelief());
	}

	@Test
	public void testDecodeStateMultiCell() throws Exception {
		CVMEncoder encoder = new CVMEncoder(convex.test.Samples.TEST_STORE);
		DecodeState ds = new DecodeState(getBeliefBlob());

		// Read top cell via DecodeState
		ACell topCell = encoder.read(ds);
		assertNotNull(topCell, "Top cell should not be null");

		// Read all child cells: each is [VLQ length][encoding]
		HashMap<Hash, ACell> children = new HashMap<>();
		int childCount = 0;
		while (ds.pos < ds.limit) {
			long len = encoder.readVLQCount(ds);
			assertTrue(len > 0, "Child encoding length must be positive");
			int childEnd = ds.pos + (int) len;
			assertTrue(childEnd <= ds.limit, "Child encoding exceeds blob bounds");

			ACell child = encoder.read(ds);
			assertNotNull(child, "Child cell should not be null");
			assertFalse(child.isEmbedded(), "Child cell should not be embedded");
			assertEquals(childEnd, ds.pos, "DecodeState pos mismatch after child read");

			children.put(child.getHash(), child);
			childCount++;
		}

		assertEquals(ds.limit, ds.pos, "DecodeState should be fully consumed");
		assertTrue(childCount > 0, "Should have at least one child cell");
	}

	@Test
	public void testRoundTrip() throws Exception {
		// Re-encode as multi-cell
		Blob reEncoded = Format.encodeMultiCell(getBelief(), true);

		// Decode the re-encoded data via DecodeState
		CVMEncoder encoder = new CVMEncoder(convex.test.Samples.TEST_STORE);
		DecodeState ds = new DecodeState(reEncoded);
		ACell topCell = encoder.read(ds);
		assertNotNull(topCell);

		// Walk all children
		while (ds.pos < ds.limit) {
			long len = encoder.readVLQCount(ds);
			int childEnd = ds.pos + (int) len;
			ACell child = encoder.read(ds);
			assertNotNull(child);
			assertEquals(childEnd, ds.pos);
		}
		assertEquals(ds.limit, ds.pos);
	}
}
