= Convex Command Line Interface
:icons:

image::convex_logo.svg[Convex Command Line Interface,200,opts=inline]

== Introduction
Convex Command Line Interface or CLI, allows you to control and setup a local Convex network and peers.


=== Overview
The CLI is part of the Convex library. The CLI has been built to do two things:

. Local Convex network.

. Local Peer(s) connected to a local network.

. Send and Query transactions with a local network.

. Local Peer connected to a remote Convex network.



== Getting Started
Currently the CLI can only be downloaded via github.

=== Get the source
You will need to visit https://github.com/Convex-Dev/convex/tree/develop[convex] and
git clone the repository onto your local computer.

At the moment the develop branch is currently the latest version.


    git clone https://github.com/Convex-Dev/convex.git
    cd convex
    git checkout develop
    git pull

=== Convex Projects
The Convex repository is made up of the following sub projects:

* *convex-benchmaks*:     Run benchmarks on the convex network.
* *convex-cli*:           This CLI
* *convex-core*:          The main convex core library.
* *convex-gui*:           A local convex network running as a GUI application.
* *convex-peer*:          Peer library used to run convex peer.

The CLI project is currently part of the main Convex repository.


=== Compile and Setup
Once you have got the latest source of Convex, you can now compile the suite of projects.

To do this you need to execute Maven install or package

    mvn install

or

    mvn package

If you wish to build without running the tests you can append the option `-DskipTests`


After building and installing the maven dependencies you should eventually see the following lines
generated by the Maven build process:

----
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for convex 0.7.0-SNAPSHOT:
[INFO]
[INFO] convex ............................................. SUCCESS [  0.146 s]
[INFO] convex-core ........................................ SUCCESS [  5.003 s]
[INFO] convex-peer ........................................ SUCCESS [  0.027 s]
[INFO] convex-gui ......................................... SUCCESS [  2.474 s]
[INFO] convex-cli ......................................... SUCCESS [  4.665 s]
[INFO] convex-benchmarks .................................. SUCCESS [  1.644 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.463 s
[INFO] Finished at: 0000-00-00T00:00:00+00:00
[INFO] ------------------------------------------------------------------------
----

=== Files needed by CLI run a local Network or Peer
The CLI needs 3 types of files to read/create/write before running a local Convex network or a Peer.
These types of files are:

. _Etch Storage database_ file. This contains the stored state of the Convex network. Usually when starting up the initial cluster the first set of peers share the same Etch database. CLI Parameter: *--etch*

. _Keystore database_ file. This file contains the private/public key pairs used for the peers and any subsequent users. CLI Parameters: *--keystore*, *--password*

. _Session_ file. This is created by the CLI to keep track of the locally running peers, so that if you want to access the local network or add another peer to the local network, the CLI will look at the session file for a randomly available peer to connect too. CLI Parameter: *--session*


== Running the CLI
Once you have successfully compiled and built Convex projects, you can now run the command line tool.

.Mac
[source,bash,role="primary"]
----
./convex help
----

.Linux
[source,bash,role="secondary"]
----
./convex help
----

.Windows
[source,bash,role="secondary"]
----
convex help

----

=== Commands
The CLI is split into commands and some sub commands they are:

Account Commands::

[cols="1,1,2"]
|===
|Command|Sub command|Description

|account, ac| |Manages convex accounts.
||balance, bal, ba |Get account balance.

||create, cr| Creates an account using a public/private key from the keystore.
You must provide a valid keystore password to the keystore.
If the keystore is not at the default location also the keystore filename.
||fund, fu|
Transfers funds to account using a public/private key from the keystore.
You must provide a valid keystore password to the keystore and a valid address.
If the keystore is not at the default location also the keystore filename.
||information, info, in|Get account information.
|===

Key Commands::
[cols="1,1,2"]
|===
|Command|Sub command|Description

|key, ke| |Manage local Convex key store.

||import, im|Import key pairs to the keystore.
||generate, ge|Generate 1 or more private key pairs.
||list, li|List available key pairs.
||export, ex|Export 1 or more key pairs from the keystore.
|===

Local Commands::
[cols="1,1,2"]
|===
|Command|Sub command|Description

|local, lo||Operates a local convex network.
||gui|Starts a local convex test network using the peer manager GUI application.
||start, st|Starts a local convex test network.
|===

Peer Commands::
[cols="1,1,2"]
|===
|Command|Sub command|Description

|peer, pe||Operates a local peer.
||create, cr|Creates a keypair, new account and a funding stake: to run a local peer.
||start, st|Starts a local peer.
|===

Query Command::
[cols="1,1"]
|===
|Command|Description

|query, qu|Execute a query on the current peer.
|===

Status Command::
[cols="1,1"]
|===
|Command|Description

|status, st|Reports on the current status of the network.
|===

Transaction Command::
[cols="1,1"]
|===
|Command|Description


|transaction, transact, tr|Execute a transaction on the network via a peer.
|===

Help Command::
[cols="1,1"]
|===
|Command|Description

|help|Displays help information about the specified command
|===

=== Requesting Help
The CLI supports help using the *-h* or *--help* options or the command *help*. For each sub command there are more help options.

So for example

    ./convex --help

will show the common options for all commands, and the list of available commands.

    ./convex local start --help

will show the common options as well as the specific options for the *convex.local.start* command

== Starting a local network
The CLI is designed to start a local Convex network. This will allow for the developer/tester to try out Convex in a local environment without
effecting any other networks.

=== Simple local start
The simplest way to start up the local Convex network is to run the following command:

    ./convex local start --password=my-password

You wil always need to pass the password to the *keystore* file since the CLI will need access to create and start up the local peers.

The CLI will automatically create 4 keypairs and place them in the keystore. The CLI will then start up 4 peers all sharing a single
temporary local _Etch Database_ in the /tmp folder.


=== Local start with preset peer keys
Whilst the simple local start will auto generate public keys for the local peers. You can always select the peer keys you wish
to use to start up a local network.

If you have already used the simple local start, you can get the list of keys created by running:

----
    ./convex key list --password=my-password

    Index Public Key
    1 6e89035fce6d842b65e7831433fb3426928865a3c8de9536cfa50a1928eb0276 <1>
    2 13e691e05dee5a2c5ad90f6802f4ac5c274582ca5332516dc4740ae55d817856
    3 8291e8976e0ee0363f98f819712552924e1dd1d8ab77c4dc8577765ee3eb2d36
    4 ce55bb850cefaf87c5a16ab7c410f942e11463d0000eb71e8a22e6ce76301b5c
    5 21076aa0c88baba170e62196b5735316f6cc1c5bfe672c0c1e5f9b85d8aaf8cb

----

<1> First keypair stored in the keystore with the public key starting with `6e89035fce6...` or at index position #1

This will show you the list of keys that have been stored in the key store.

To start up the local Convex network with the first 4 public keys you can run the following command:

    ./convex local start --public-key=6e89035 --public-key=13e691e --public-key=8291e8976 --public-key=ce55bb8 --password=my-password

or you can combine the public key fields into a single comma seperated list

    ./convex local start --public-key=6e89035,13e691e,8291e8976,ce55bb8 --password=my-password

This will now start up a local Convex network with 4 peers using the same public keys for each peer.

[TIP]
====
To start the same peers using the same public keys you can also use the index number in the keystore. So the line:

    ./convex local start --index-key=1,2,3,4 --password=my-password

Will start the same set of peers as above using the first 4 key pairs from the keystore.
====


==== Config Parameters for convex.local.start
.convex.conf
----
    # if no database file is provided then the CLI will create a
    # temporary etch storage database at /tmp/etchxxx.tmp
    convex.etch=

    # default keystore filename
    convex.keystore =$HOME/.convex/keystore.pfx

    # default session filename
    convex.session = $HOME/.convex/session.conf

    # number of peers to start
    convex.local.start=4

    # comma list of index of keys or items
    convex.local.index-key=

    # comma list of public-key hex values, or multiple items
    convex.local.public-key=

    # keystore password
    convex.local.password=
----


== Starting a local Peer
How to start a local peer, and join a local Convex network.

== Starting a local Peer to a remote Convex network
How to start a local peer, that connects to a remote Convex network.

== Starting the GUI local network
How to start the gui local network.

== Managing your Keys - The Keystore
To run any peer you need to manage the local public/private key pairs.

== Managing Accounts
Information on how to create, fund and get information about the local accounts.

=== Create an account
How to create a local account

=== Get an accounts balance
How to get an account's balance

=== Request funds for an account
How to request funds for an account

=== Get information about an account
How to get information about an account

== Queries
How to execute queries on a local Convex network.

== Trancsactions
How to execute transactions on a local Convex network.







