= Convex Command Line Interface

image::convex_logo.svg[Convex Command Line Interface,200,opts=inline]


== Introduction
Convex Command Line Interface or CLI, allows you to control and setup a local Convex network and peers.


=== Overview
The CLI is part of the Convex library.

== Getting Started
Currently the CLI can only be downloaded via github.

=== Get the source
You will need to visit https://github.com/Convex-Dev/convex/tree/develop[convex] and
git clone the repository onto your local computer.

At the moment the develop branch is currently the latest version.


    git clone https://github.com/Convex-Dev/convex.git
    cd convex
    git checkout develop
    git pull

=== The Sub Projects
The Convex repository is made up of the following sub projects:

* convex-benchmaks:     Run benchmarks on the convex network.
* convex-cli:           This CLI
* convex-core:          The main convex core library.
* convex-gui:           A local convex network running as a GUI application.
* convex-peer:          Peer library used to run convex peer.

The CLI project is currently part of the main Convex repository.


=== Compile and Setup
Once you have got the latest source of Convex, you can now compile the suite of projects.

To do this you need to execute Maven install or package

    mvn install

or

    mvn package

If you wish to build without running the tests you can append the option `-DskipTests`


After building and installing the maven dependencies you should eventually see the following lines
generated by the Maven build process:

----
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for convex 0.7.0-SNAPSHOT:
[INFO]
[INFO] convex ............................................. SUCCESS [  0.146 s]
[INFO] convex-core ........................................ SUCCESS [  5.003 s]
[INFO] convex-peer ........................................ SUCCESS [  0.027 s]
[INFO] convex-gui ......................................... SUCCESS [  2.474 s]
[INFO] convex-cli ......................................... SUCCESS [  4.665 s]
[INFO] convex-benchmarks .................................. SUCCESS [  1.644 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.463 s
[INFO] Finished at: 2021-07-28T17:46:09+08:00
[INFO] ------------------------------------------------------------------------
----

== Running the CLI
Once you have successfully compiled and built Convex projects, you can now run the command line tool.

.Mac
[source,bash,role="primary"]
----
./convex help
----

.Linux
[source,bash,role="secondary"]
----
./convex help
----

.Windows
[source,bash,role="secondary"]
----
convex help

----





