package convex.core.cvm;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.util.HashMap;

import org.junit.jupiter.api.Test;

import convex.core.data.ACell;
import convex.core.data.AEncoder.DecodeState;
import convex.core.data.Blob;
import convex.core.data.Format;
import convex.core.data.Hash;
/**
 * Tests decoding a real genesis state from CAD3 multi-cell format
 * using the DecodeState path.
 *
 * genesis.cad3 is committed to test resources (generated by AcquireGenesis).
 */
public class GenesisStateTest {

	static final String GENESIS_HASH = "b0e44f2a645abfa539f5b96b7a0eabb0f902866feaff0f7c12d1213e02333f13";

	private static Blob genesisBlob;
	private static State genesisState;

	public static synchronized Blob getGenesisBlob() {
		if (genesisBlob == null) loadGenesis();
		return genesisBlob;
	}

	public static synchronized State getGenesisState() {
		if (genesisState == null) loadGenesis();
		return genesisState;
	}

	private static void loadGenesis() {
		try (InputStream is = GenesisStateTest.class.getResourceAsStream("/genesis.cad3")) {
			assertNotNull(is, "genesis.cad3 not found in test resources");
			genesisBlob = Blob.wrap(is.readAllBytes());
		} catch (Exception e) {
			throw new RuntimeException("Failed to load genesis.cad3", e);
		}
		assertTrue(genesisBlob.count() > 100, "Genesis file too small");

		try {
			ACell result = Format.decodeMultiCell(genesisBlob);
			assertInstanceOf(State.class, result);
			genesisState = (State) result;
		} catch (Exception e) {
			throw new RuntimeException("Failed to decode genesis.cad3", e);
		}
	}

	@Test
	public void testGenesisHash() {
		assertEquals(GENESIS_HASH, getGenesisState().getHash().toHexString());
	}

	@Test
	public void testStateRecord() {
		StateTest.doStateTests(getGenesisState());
	}

	@Test
	public void testDecodeStateMultiCell() throws Exception {
		CVMEncoder encoder = CVMEncoder.INSTANCE;
		DecodeState ds = new DecodeState(getGenesisBlob());

		// Read top cell via DecodeState
		ACell topCell = encoder.read(ds);
		assertNotNull(topCell, "Top cell should not be null");

		// Read all child cells: each is [VLQ length][encoding]
		HashMap<Hash, ACell> children = new HashMap<>();
		int childCount = 0;
		while (ds.pos < ds.limit) {
			long len = encoder.readVLQCount(ds);
			assertTrue(len > 0, "Child encoding length must be positive");
			int childEnd = ds.pos + (int) len;
			assertTrue(childEnd <= ds.limit, "Child encoding exceeds blob bounds");

			ACell child = encoder.read(ds);
			assertNotNull(child, "Child cell should not be null");
			assertFalse(child.isEmbedded(), "Child cell should not be embedded");
			assertEquals(childEnd, ds.pos, "DecodeState pos mismatch after child read");

			children.put(child.getHash(), child);
			childCount++;
		}

		assertEquals(ds.limit, ds.pos, "DecodeState should be fully consumed");
		assertTrue(childCount > 0, "Should have at least one child cell");
	}

	@Test
	public void testRoundTrip() throws Exception {
		// Re-encode as multi-cell
		Blob reEncoded = Format.encodeMultiCell(getGenesisState(), true);

		// Decode the re-encoded data via DecodeState
		CVMEncoder encoder = CVMEncoder.INSTANCE;
		DecodeState ds = new DecodeState(reEncoded);
		ACell topCell = encoder.read(ds);
		assertNotNull(topCell);

		// Walk all children
		while (ds.pos < ds.limit) {
			long len = encoder.readVLQCount(ds);
			int childEnd = ds.pos + (int) len;
			ACell child = encoder.read(ds);
			assertNotNull(child);
			assertEquals(childEnd, ds.pos);
		}
		assertEquals(ds.limit, ds.pos);
	}
}
